# Generated by Django 5.0.6 on 2024-07-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip_code",
            field=models.CharField(default="-", max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="store_custo_last_na_e6a359_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="customer",
            table="store_customers",
        ),
    ]
