# Generated by Django 5.0.6 on 2024-07-04 05:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_remove_customer_store_custo_last_na_2e448d_idx_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="unit_price",
        ),
    ]
