# Generated by Django 5.0.6 on 2024-07-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_rename_price_product_unit_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="zip_code",
        ),
        migrations.AddField(
            model_name="customer",
            name="membership",
            field=models.CharField(
                choices=[("B", "Bronze"), ("S", "Silver"), ("G", "Gold")],
                default="B",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("P", "Pending"), ("C", "Complete"), ("F", "Failed")],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(),
        ),
    ]
